### ISSUE TITLE
output image doesn't allow me to `su` to a new user

### ISSUE THREAD

**Issue by cyphar** [brauner/docker-melt#1]
If I generate a new image using `melt`:

```
% docker save opensuse/amd64:tumbleweed > tumbleweed.tar
% ./melt -i tumbleweed.tar -o tumbleweed-squashed.tar -t tmp
% docker import tumbleweed-squashed.tar tumbleweed:squashed
% docker run -it tumbleweed:squashed sh
sh-4.3# useradd user
sh-4.3# su user
su: failed to execute /bin/bash: Permission denied
```

Which doesn't look right.

**Comment by brauner** [comment]
Thanks @cyphar. If I find the time this week I'll try to fix those (patches welcome). I'll probably rewrite some parts of it anyway using the `diff-ids` layer array in the json configuration file.

**Comment by brauner** [comment]
This looks like a permissions problem for `/` due to tarring the file.

**Comment by brauner** [comment]
Should be fixed by https://github.com/brauner/melt/commit/641e06b755ef080e83cd67da2ea27ba5fdc10bb6.

**Comment by cyphar** [comment]
Yup, this fixed this issue. Thanks! :D
