### ISSUE TITLE
output image doesn't reduce file size with redundant layers

### ISSUE THREAD

**Issue by cyphar** [brauner/docker-melt#2]
If I have a `Dockerfile` like this:

```
FROM opensuse/amd64:tumbleweed

RUN truncate --size 200M /somefile
RUN unlink /somefile
```

The resultant image is 200M larger than is necessary. When using `melt` the resultant rootfs doesn't appear to realise that the file can be removed. Docker does appear to prioritise removal of files over their creation, which means that this doesn't cause effects like files sticking around even though they were removed.

You might want to look at how "whiteout" files are implemented.

**Comment by brauner** [comment]
Should be possible with https://github.com/brauner/melt/commit/db5896ff16bac0bb16c1ac0070ee7ad8dbeb71b5 by specifying `-w`.

**Comment by cyphar** [comment]
There's actually still a few issues with it (it doesn't get applied per-layer so something like

```
FROM opensuse/amd64:tumbleweed

RUN truncate --size 200M /somefile
RUN unlink /somefile
RUN echo "another" > /somefile
```

will still cause issues -- but don't worry about it, it's a very weird edge case). Mad props for writing this in C though. :smile_cat:

**Comment by brauner** [comment]
That's a sneaky edge case. Cool. :) Thanks!
